// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CancelJobData, CancelJobErrors, CancelJobResponses, ChatAiChatPostData, ChatAiChatPostErrors, ChatAiChatPostResponses, DownloadEnhancedMuscleDownloadFilenameGetData, DownloadEnhancedMuscleDownloadFilenameGetErrors, DownloadEnhancedMuscleDownloadFilenameGetResponses, GetJobData, GetJobErrors, GetJobResponses, HealthHealthGetData, HealthHealthGetResponses, PostBeatSyncData, PostBeatSyncErrors, PostBeatSyncResponses, PostMoodDnaData, PostMoodDnaErrors, PostMoodDnaResponses, PostMuscleEnhanceData, PostMuscleEnhanceErrors, PostMuscleEnhanceResponses, PostStyleCompareData, PostStyleCompareErrors, PostStyleCompareResponses, PostViralCutData, PostViralCutErrors, PostViralCutResponses, VoiceCommandEditorVoiceCommandPostData, VoiceCommandEditorVoiceCommandPostErrors, VoiceCommandEditorVoiceCommandPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Chat
 */
export const chatAiChatPost = <ThrowOnError extends boolean = false>(options: Options<ChatAiChatPostData, ThrowOnError>): RequestResult<ChatAiChatPostResponses, ChatAiChatPostErrors, ThrowOnError> => (options.client ?? client).post<ChatAiChatPostResponses, ChatAiChatPostErrors, ThrowOnError>({
    url: '/ai/chat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Beat Sync
 */
export const postBeatSync = <ThrowOnError extends boolean = false>(options: Options<PostBeatSyncData, ThrowOnError>): RequestResult<PostBeatSyncResponses, PostBeatSyncErrors, ThrowOnError> => (options.client ?? client).post<PostBeatSyncResponses, PostBeatSyncErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/editor/beat-sync',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Viral Cut
 */
export const postViralCut = <ThrowOnError extends boolean = false>(options: Options<PostViralCutData, ThrowOnError>): RequestResult<PostViralCutResponses, PostViralCutErrors, ThrowOnError> => (options.client ?? client).post<PostViralCutResponses, PostViralCutErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/editor/viral-cut',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Voice Command
 */
export const voiceCommandEditorVoiceCommandPost = <ThrowOnError extends boolean = false>(options: Options<VoiceCommandEditorVoiceCommandPostData, ThrowOnError>): RequestResult<VoiceCommandEditorVoiceCommandPostResponses, VoiceCommandEditorVoiceCommandPostErrors, ThrowOnError> => (options.client ?? client).post<VoiceCommandEditorVoiceCommandPostResponses, VoiceCommandEditorVoiceCommandPostErrors, ThrowOnError>({
    url: '/editor/voice-command',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>): RequestResult<HealthHealthGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Get Job
 *
 * Progress, percent, eta, and error for one job. 404 if the id is unknown.
 */
export const getJob = <ThrowOnError extends boolean = false>(options: Options<GetJobData, ThrowOnError>): RequestResult<GetJobResponses, GetJobErrors, ThrowOnError> => (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({ url: '/jobs/{job_id}', ...options });

/**
 * Cancel Job
 *
 * Ask a running job to stop. The worker drops the partial file on the next frame.
 */
export const cancelJob = <ThrowOnError extends boolean = false>(options: Options<CancelJobData, ThrowOnError>): RequestResult<CancelJobResponses, CancelJobErrors, ThrowOnError> => (options.client ?? client).post<CancelJobResponses, CancelJobErrors, ThrowOnError>({ url: '/jobs/{job_id}/cancel', ...options });

/**
 * Mood Dna
 */
export const postMoodDna = <ThrowOnError extends boolean = false>(options: Options<PostMoodDnaData, ThrowOnError>): RequestResult<PostMoodDnaResponses, PostMoodDnaErrors, ThrowOnError> => (options.client ?? client).post<PostMoodDnaResponses, PostMoodDnaErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/mood-dna',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Download Enhanced
 */
export const downloadEnhancedMuscleDownloadFilenameGet = <ThrowOnError extends boolean = false>(options: Options<DownloadEnhancedMuscleDownloadFilenameGetData, ThrowOnError>): RequestResult<DownloadEnhancedMuscleDownloadFilenameGetResponses, DownloadEnhancedMuscleDownloadFilenameGetErrors, ThrowOnError> => (options.client ?? client).get<DownloadEnhancedMuscleDownloadFilenameGetResponses, DownloadEnhancedMuscleDownloadFilenameGetErrors, ThrowOnError>({ url: '/muscle/download/{filename}', ...options });

/**
 * Muscle Enhance
 */
export const postMuscleEnhance = <ThrowOnError extends boolean = false>(options: Options<PostMuscleEnhanceData, ThrowOnError>): RequestResult<PostMuscleEnhanceResponses, PostMuscleEnhanceErrors, ThrowOnError> => (options.client ?? client).post<PostMuscleEnhanceResponses, PostMuscleEnhanceErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/muscle/enhance',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Style Compare
 */
export const postStyleCompare = <ThrowOnError extends boolean = false>(options: Options<PostStyleCompareData, ThrowOnError>): RequestResult<PostStyleCompareResponses, PostStyleCompareErrors, ThrowOnError> => (options.client ?? client).post<PostStyleCompareResponses, PostStyleCompareErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/style-match/compare',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
