// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * Body_post_beat_sync
 */
export type BodyPostBeatSync = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_post_mood_dna
 */
export type BodyPostMoodDna = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_post_muscle_enhance
 */
export type BodyPostMuscleEnhance = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Intensity
     */
    intensity?: number;
    /**
     * Preset
     */
    preset?: string;
};

/**
 * Body_post_style_compare
 */
export type BodyPostStyleCompare = {
    /**
     * Reference
     */
    reference: Blob | File;
    /**
     * Source
     */
    source: Blob | File;
};

/**
 * Body_post_viral_cut
 */
export type BodyPostViralCut = {
    /**
     * File
     */
    file: Blob | File;
    /**
     * Target Duration
     */
    target_duration?: number;
};

/**
 * ChatReq
 */
export type ChatReq = {
    /**
     * Message
     */
    message: string;
    /**
     * Language
     */
    language?: string;
};

/**
 * ExportBody
 */
export type ExportBody = {
    /**
     * W
     */
    w: number;
    /**
     * H
     */
    h: number;
    /**
     * Fps
     */
    fps: number;
    /**
     * Codec
     */
    codec: string;
    /**
     * Clips
     */
    clips?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Output Name
     */
    output_name?: string;
    /**
     * Overwrite
     */
    overwrite?: boolean;
    /**
     * Crf
     */
    crf?: number;
    /**
     * Pace
     */
    pace?: string;
    /**
     * Mix
     */
    mix?: string;
    /**
     * Audio Codec
     */
    audio_codec?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobAccepted
 *
 * POST of a heavy endpoint. Poll GET /jobs/{job_id} for the result.
 */
export type JobAccepted = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Status
     */
    status: string;
};

/**
 * JobView
 */
export type JobView = {
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress: number;
    /**
     * Percent
     */
    percent: number;
    /**
     * Eta S
     */
    eta_s?: number | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Result
     */
    result?: {
        [key: string]: unknown;
    } | null;
    /**
     * Output Filename
     */
    output_filename?: string | null;
    /**
     * Partial Removed
     */
    partial_removed?: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VoiceReq
 */
export type VoiceReq = {
    /**
     * Text
     */
    text: string;
};

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type GetJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Successful Response
     */
    200: JobView;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type CancelJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}/cancel';
};

export type CancelJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelJobError = CancelJobErrors[keyof CancelJobErrors];

export type CancelJobResponses = {
    /**
     * Successful Response
     */
    200: JobView;
};

export type CancelJobResponse = CancelJobResponses[keyof CancelJobResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatAiChatPostData = {
    body: ChatReq;
    path?: never;
    query?: never;
    url: '/ai/chat';
};

export type ChatAiChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatAiChatPostError = ChatAiChatPostErrors[keyof ChatAiChatPostErrors];

export type ChatAiChatPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostBeatSyncData = {
    body: BodyPostBeatSync;
    path?: never;
    query?: never;
    url: '/editor/beat-sync';
};

export type PostBeatSyncErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostBeatSyncError = PostBeatSyncErrors[keyof PostBeatSyncErrors];

export type PostBeatSyncResponses = {
    /**
     * Successful Response
     */
    202: JobAccepted;
};

export type PostBeatSyncResponse = PostBeatSyncResponses[keyof PostBeatSyncResponses];

export type PostViralCutData = {
    body: BodyPostViralCut;
    path?: never;
    query?: never;
    url: '/editor/viral-cut';
};

export type PostViralCutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostViralCutError = PostViralCutErrors[keyof PostViralCutErrors];

export type PostViralCutResponses = {
    /**
     * Successful Response
     */
    202: JobAccepted;
};

export type PostViralCutResponse = PostViralCutResponses[keyof PostViralCutResponses];

export type PostMoodDnaData = {
    body: BodyPostMoodDna;
    path?: never;
    query?: never;
    url: '/mood-dna';
};

export type PostMoodDnaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostMoodDnaError = PostMoodDnaErrors[keyof PostMoodDnaErrors];

export type PostMoodDnaResponses = {
    /**
     * Successful Response
     */
    202: JobAccepted;
};

export type PostMoodDnaResponse = PostMoodDnaResponses[keyof PostMoodDnaResponses];

export type PostMuscleEnhanceData = {
    body: BodyPostMuscleEnhance;
    path?: never;
    query?: never;
    url: '/muscle/enhance';
};

export type PostMuscleEnhanceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostMuscleEnhanceError = PostMuscleEnhanceErrors[keyof PostMuscleEnhanceErrors];

export type PostMuscleEnhanceResponses = {
    /**
     * Successful Response
     */
    202: JobAccepted;
};

export type PostMuscleEnhanceResponse = PostMuscleEnhanceResponses[keyof PostMuscleEnhanceResponses];

export type DownloadEnhancedMuscleDownloadFilenameGetData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/muscle/download/{filename}';
};

export type DownloadEnhancedMuscleDownloadFilenameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadEnhancedMuscleDownloadFilenameGetError = DownloadEnhancedMuscleDownloadFilenameGetErrors[keyof DownloadEnhancedMuscleDownloadFilenameGetErrors];

export type DownloadEnhancedMuscleDownloadFilenameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VoiceCommandEditorVoiceCommandPostData = {
    body: VoiceReq;
    path?: never;
    query?: never;
    url: '/editor/voice-command';
};

export type VoiceCommandEditorVoiceCommandPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VoiceCommandEditorVoiceCommandPostError = VoiceCommandEditorVoiceCommandPostErrors[keyof VoiceCommandEditorVoiceCommandPostErrors];

export type VoiceCommandEditorVoiceCommandPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostStyleCompareData = {
    body: BodyPostStyleCompare;
    path?: never;
    query?: never;
    url: '/style-match/compare';
};

export type PostStyleCompareErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostStyleCompareError = PostStyleCompareErrors[keyof PostStyleCompareErrors];

export type PostStyleCompareResponses = {
    /**
     * Successful Response
     */
    202: JobAccepted;
};

export type PostStyleCompareResponse = PostStyleCompareResponses[keyof PostStyleCompareResponses];

export type PostExportData = {
    body: ExportBody;
    path?: never;
    query?: never;
    url: '/export';
};

export type PostExportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostExportError = PostExportErrors[keyof PostExportErrors];

export type PostExportResponses = {
    /**
     * Successful Response
     */
    202: JobAccepted;
};

export type PostExportResponse = PostExportResponses[keyof PostExportResponses];
